version: "3"

services:
    django:
        container_name: "nuitdelinfo_2021"
        build: ./
        image: nuitdelinfo_2021
        ports:
            - "8001:8000"
        volumes:
            - "django:/nuitdelinfo_2021/"

    postgres:
        container_name: "nuitdelinfo_2021_db"
        image: postgres
        environment:
            POSTGRES_PASSWORD: nuitdelinfo_2021
            POSTGRES_USER: nuitdelinfo_2021
            POSTGRES_DB: nuitdelinfo_2021
        volumes:
            - "db:/var/lib/postgresql/data"

volumes:
    django:
    db:
