# Generated by Django 3.2.9 on 2021-12-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20211202_2225'),
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='pending_edit_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.people'),
        ),
        migrations.AddField(
            model_name='boat',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
