# Generated by Django 3.2.9 on 2021-12-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('birth', models.DateField()),
                ('death', models.DateField()),
                ('history', models.TextField()),
                ('genealogy', models.TextField()),
                ('awards', models.TextField()),
                ('pro_life', models.TextField()),
                ('testimonials', models.TextField()),
                ('sources', models.TextField()),
            ],
        ),
    ]
