# Generated by Django 3.2.9 on 2021-12-02 21:27

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='awards',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='death',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='genealogy',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='history',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='pro_life',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='sources',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='testimonials',
            field=django_quill.fields.QuillField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
