# Generated by Django 3.2.9 on 2021-12-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('location_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('resume', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('sources', models.TextField()),
                ('rescuers', models.ManyToManyField(related_name='rescued', to='people.People')),
                ('saved', models.ManyToManyField(related_name='saved', to='people.People')),
            ],
        ),
    ]
