# Generated by Django 3.2.9 on 2021-12-02 23:01

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='sources',
            field=django_quill.fields.QuillField(),
        ),
    ]
